// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wielerspel.Api.Data;

#nullable disable

namespace Wielerspel.Api.Migrations
{
    [DbContext(typeof(WielerspelDbContext))]
    [Migration("20260818192911_AddCyclistSelectionHistory")]
    partial class AddCyclistSelectionHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wielerspel.Api.Models.Competition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Budget")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxTransfers")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TeamLockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TeamSize")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Competitions");
                });

            modelBuilder.Entity("Wielerspel.Api.Models.CompetitionCyclist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CyclistId")
                        .HasColumnType("uuid");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CyclistId");

                    b.HasIndex("CompetitionId", "CyclistId")
                        .IsUnique();

                    b.ToTable("CompetitionCyclists");
                });

            modelBuilder.Entity("Wielerspel.Api.Models.CompetitionFinalStanding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FinalizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CompetitionId", "Position")
                        .IsUnique();

                    b.HasIndex("CompetitionId", "UserId")
                        .IsUnique();

                    b.ToTable("CompetitionFinalStandings");
                });

            modelBuilder.Entity("Wielerspel.Api.Models.CompetitionUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("TeamLocked")
                        .HasColumnType("boolean");

                    b.Property<int>("TransfersUsed")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CompetitionId", "UserId")
                        .IsUnique();

                    b.ToTable("CompetitionUsers");
                });

            modelBuilder.Entity("Wielerspel.Api.Models.CompetitionUserCyclist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionCyclistId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("JokerStageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionCyclistId");

                    b.HasIndex("JokerStageId");

                    b.HasIndex("CompetitionUserId", "CompetitionCyclistId")
                        .IsUnique();

                    b.HasIndex("CompetitionUserId", "JokerStageId")
                        .IsUnique()
                        .HasFilter("\"JokerStageId\" IS NOT NULL");

                    b.ToTable("CompetitionUserCyclists");
                });

            modelBuilder.Entity("Wielerspel.Api.Models.CompetitionUserCyclistHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionCyclistId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionUserCyclistId")
                        .HasColumnType("uuid");

                    b.Property<int>("FromStageNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("ToStageNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionCyclistId");

                    b.HasIndex("CompetitionUserCyclistId", "FromStageNumber")
                        .IsUnique();

                    b.ToTable("CompetitionUserCyclistHistories");
                });

            modelBuilder.Entity("Wielerspel.Api.Models.Cyclist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Cyclists");
                });

            modelBuilder.Entity("Wielerspel.Api.Models.Stage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FinishLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("GreenJerseyCompetitionCyclistId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PolkaDotJerseyCompetitionCyclistId")
                        .HasColumnType("uuid");

                    b.Property<bool>("ResultsPublished")
                        .HasColumnType("boolean");

                    b.Property<int>("StageNumber")
                        .HasColumnType("integer");

                    b.Property<string>("StartLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WhiteJerseyCompetitionCyclistId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("YellowJerseyCompetitionCyclistId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GreenJerseyCompetitionCyclistId");

                    b.HasIndex("PolkaDotJerseyCompetitionCyclistId");

                    b.HasIndex("WhiteJerseyCompetitionCyclistId");

                    b.HasIndex("YellowJerseyCompetitionCyclistId");

                    b.HasIndex("CompetitionId", "StageNumber")
                        .IsUnique();

                    b.ToTable("Stages");
                });

            modelBuilder.Entity("Wielerspel.Api.Models.StageResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionCyclistId")
                        .HasColumnType("uuid");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionCyclistId");

                    b.HasIndex("StageId", "CompetitionCyclistId")
                        .IsUnique();

                    b.HasIndex("StageId", "Position")
                        .IsUnique();

                    b.ToTable("StageResults");
                });

            modelBuilder.Entity("Wielerspel.Api.Models.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Wielerspel.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordResetTokenHash")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Wielerspel.Api.Models.CompetitionCyclist", b =>
                {
                    b.HasOne("Wielerspel.Api.Models.Competition", "Competition")
                        .WithMany("CompetitionCyclists")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wielerspel.Api.Models.Cyclist", "Cyclist")
                        .WithMany("CompetitionCyclists")
                        .HasForeignKey("CyclistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");

                    b.Navigation("Cyclist");
                });

            modelBuilder.Entity("Wielerspel.Api.Models.CompetitionFinalStanding", b =>
                {
                    b.HasOne("Wielerspel.Api.Models.Competition", "Competition")
                        .WithMany("FinalStandings")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wielerspel.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Wielerspel.Api.Models.CompetitionUser", b =>
                {
                    b.HasOne("Wielerspel.Api.Models.Competition", "Competition")
                        .WithMany("CompetitionUsers")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wielerspel.Api.Models.User", "User")
                        .WithMany("CompetitionUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Wielerspel.Api.Models.CompetitionUserCyclist", b =>
                {
                    b.HasOne("Wielerspel.Api.Models.CompetitionCyclist", "CompetitionCyclist")
                        .WithMany("CompetitionUserCyclists")
                        .HasForeignKey("CompetitionCyclistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wielerspel.Api.Models.CompetitionUser", "CompetitionUser")
                        .WithMany("Cyclists")
                        .HasForeignKey("CompetitionUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wielerspel.Api.Models.Stage", "JokerStage")
                        .WithMany()
                        .HasForeignKey("JokerStageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CompetitionCyclist");

                    b.Navigation("CompetitionUser");

                    b.Navigation("JokerStage");
                });

            modelBuilder.Entity("Wielerspel.Api.Models.CompetitionUserCyclistHistory", b =>
                {
                    b.HasOne("Wielerspel.Api.Models.CompetitionCyclist", "CompetitionCyclist")
                        .WithMany()
                        .HasForeignKey("CompetitionCyclistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wielerspel.Api.Models.CompetitionUserCyclist", "CompetitionUserCyclist")
                        .WithMany()
                        .HasForeignKey("CompetitionUserCyclistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompetitionCyclist");

                    b.Navigation("CompetitionUserCyclist");
                });

            modelBuilder.Entity("Wielerspel.Api.Models.Cyclist", b =>
                {
                    b.HasOne("Wielerspel.Api.Models.Team", "Team")
                        .WithMany("Cyclists")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Wielerspel.Api.Models.Stage", b =>
                {
                    b.HasOne("Wielerspel.Api.Models.Competition", "Competition")
                        .WithMany("Stages")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wielerspel.Api.Models.CompetitionCyclist", "GreenJerseyCompetitionCyclist")
                        .WithMany()
                        .HasForeignKey("GreenJerseyCompetitionCyclistId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Wielerspel.Api.Models.CompetitionCyclist", "PolkaDotJerseyCompetitionCyclist")
                        .WithMany()
                        .HasForeignKey("PolkaDotJerseyCompetitionCyclistId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Wielerspel.Api.Models.CompetitionCyclist", "WhiteJerseyCompetitionCyclist")
                        .WithMany()
                        .HasForeignKey("WhiteJerseyCompetitionCyclistId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Wielerspel.Api.Models.CompetitionCyclist", "YellowJerseyCompetitionCyclist")
                        .WithMany()
                        .HasForeignKey("YellowJerseyCompetitionCyclistId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Competition");

                    b.Navigation("GreenJerseyCompetitionCyclist");

                    b.Navigation("PolkaDotJerseyCompetitionCyclist");

                    b.Navigation("WhiteJerseyCompetitionCyclist");

                    b.Navigation("YellowJerseyCompetitionCyclist");
                });

            modelBuilder.Entity("Wielerspel.Api.Models.StageResult", b =>
                {
                    b.HasOne("Wielerspel.Api.Models.CompetitionCyclist", "CompetitionCyclist")
                        .WithMany("StageResults")
                        .HasForeignKey("CompetitionCyclistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wielerspel.Api.Models.Stage", "Stage")
                        .WithMany("Results")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompetitionCyclist");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("Wielerspel.Api.Models.Competition", b =>
                {
                    b.Navigation("CompetitionCyclists");

                    b.Navigation("CompetitionUsers");

                    b.Navigation("FinalStandings");

                    b.Navigation("Stages");
                });

            modelBuilder.Entity("Wielerspel.Api.Models.CompetitionCyclist", b =>
                {
                    b.Navigation("CompetitionUserCyclists");

                    b.Navigation("StageResults");
                });

            modelBuilder.Entity("Wielerspel.Api.Models.CompetitionUser", b =>
                {
                    b.Navigation("Cyclists");
                });

            modelBuilder.Entity("Wielerspel.Api.Models.Cyclist", b =>
                {
                    b.Navigation("CompetitionCyclists");
                });

            modelBuilder.Entity("Wielerspel.Api.Models.Stage", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("Wielerspel.Api.Models.Team", b =>
                {
                    b.Navigation("Cyclists");
                });

            modelBuilder.Entity("Wielerspel.Api.Models.User", b =>
                {
                    b.Navigation("CompetitionUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
